name: air-quality-daily

on:
  schedule:
    - cron: '11 6 * * *'
  workflow_dispatch:

jobs:
  schedule_pipelines:
    runs-on: ubuntu-latest
    name: python

    permissions:
      pages: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: execute python workflows from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: |
          uv run ipython 2_air_quality_feature_pipeline.ipynb 
          uv run ipython 4_air_quality_batch_inference.ipynb
